<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitecd84da54ecddd7f31a45f6fa51e2edd
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitecd84da54ecddd7f31a45f6fa51e2edd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitecd84da54ecddd7f31a45f6fa51e2edd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitecd84da54ecddd7f31a45f6fa51e2edd::$classMap;

        }, null, ClassLoader::class);
    }
}
